[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-expand = "1.0.118"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.111"
enum_as_str_derive = { path = "./enum_as_str_derive" }